In [ ]:
#1. What is a Python library? Why do we use Python libraries?

(a)Python library is simply a collection of codes or modules of codes that we can use in a program for specific operations. We use libraries so that we don’t need to write the code again in our program that is already available. But how it works. Actually, in the MS Windows environment, the library files have a DLL extension (Dynamic Load Libraries). When we link a library with our program and run that program, the linker automatically searches for that library. It extracts the functionalities of that library and interprets the program accordingly. That’s how we use the methods of a library in our program. 

(b)The Python Standard Library contains the exact syntax, semantics, and tokens of Python. It contains built-in modules that provide access to basic system functionality like I/O and some other core modules. Most of the Python Libraries are written in the C programming language. The Python standard library consists of more than 200 core modules. All these work together to make Python a high-level programming language. Python Standard Library plays a very important role. Without it, the programmers can’t have access to the functionalities of Python. But other than this, there are several other libraries in Python that make a programmer’s life easier.

(c)
Use of Libraries in Python Program
As we write large-size programs in Python, we want to maintain the code’s modularity. For the easy maintenance of the code, we split the code into different parts and we can use that code later ever we need it. In Python, modules play that part. Instead of using the same code in different programs and making the code complex, we define mostly used functions in modules and we can just simply import them in a program wherever there is a requirement. We don’t need to write that code but still, we can use its functionality by importing its module. Multiple interrelated modules are stored in a library. And whenever we need to use a module, we import it from its library. In Python, it’s a very simple job to do due to its easy syntax. We just need to use import.

In [ ]:
#2.What is the difference between Numpy array and List?

(a)Numpy array:
NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data. 

Some important points about Numpy arrays:

We can create an N-dimensional array in Python using Numpy.array().
The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (Note You can also create a structured array in Python).
Element-wise operation is possible.

import numpy as np
 
a = np.array([1, 2, 3])
print(a)

(b)What is Python List?
A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets. 

Some important points about Python Lists:

The list can be homogeneous or heterogeneous.
Element-wise operation is not possible on the list.
Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list

Var = ["Geeks", "for", "Geeks"]
print(Var)


In [6]:
#3. Find the shape, size and dimension of the following array?

import numpy as npy
 

arr1 = npy.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
 

print("Shape",arr1.shape)

print("Dimensions in _1darr are: ",arr1.ndim)

print(arr1.size)


Shape (3, 4)
Dimensions in _1darr are:  2
12


In [4]:
# Write python code to access the first row of the following array?

#[[1, 2, 3, 4]

#[5, 6, 7, 8],

#[9, 10, 11, 12]

# Importing the NumPy library and aliasing it as 'np'
import numpy as npy

# Creating a NumPy array 'arra_data' containing integers from 0 to 15 and reshaping it into a 4x4 matrix
arra_data = npy.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

# Displaying a message indicating the original array will be printed
print("Original array:")

# Printing the original 4x4 array 'arra_data'
print(arra_data)

# Displaying a message indicating the extracted data (first row)
print("\nExtracted data: First row")

# Printing the first row of the 'arra_data' array using slicing
print(arra_data[0]) 

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Extracted data: First row
[1 2 3 4]


In [12]:
#5.How do you access the element at the third row and fourth column from the given numpy array

import numpy as np
 
array = npy.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

# defining array
arr = np.array(array)
 
print('printing 3th row')
print(arr[2, :])
 
print('printing 4nd column')
print(arr[:, 3])
 


printing 3th row
[ 9 10 11 12]
printing 4nd column
[ 4  8 12]


In [30]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

# Creating a NumPy array 'x' using arange() from 0 to 1 and reshaping it into a 3x3 matrix
x = np.arange(start = 0, stop = 1,step=0.12, dtype = 'float').reshape(3,3)


print(x)

[[0.   0.12 0.24]
 [0.36 0.48 0.6 ]
 [0.72 0.84 0.96]]


In [ ]:
#8.Describe the difference between np.random.rand and np.random.randn?

1.numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution (in the range [0,1]).

2.np.random.rand is for Uniform distribution (in the half-open interval [0.0, 1.0))
np.random.randn is for Standard Normal (aka. Gaussian) distribution (mean 0 and variance 1)
We can visually explore the differences between these two very easily:

import numpy as np
import matplotlib.pyplot as plt

sample_size = 100000
uniform = np.random.rand(sample_size)
normal = np.random.randn(sample_size)

pdf, bins, patches = plt.hist(uniform, bins=20, range=(0, 1), density=True)
plt.title('rand: uniform')
plt.show()

pdf, bins, patches = plt.hist(normal, bins=20, range=(-4, 4), density=True)
plt.title('randn: normal')
plt.show()

In [42]:
#9 Write code to increase the dimension of the following array?

import numpy as np
 
def main():
 
    # initialising array
    print('Initialised array')
    gfg = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
    print(gfg)
 
    # checking current shape
    print('current shape of the array')
    print(gfg.shape)
     
    # modifying array according to new dimensions
    print('changing shape to 4,3')
    gfg.shape = (4, 3)
    print(gfg)
 
if __name__ == "__main__":
    main()

Initialised array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
current shape of the array
(3, 4)
changing shape to 4,3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
#10 How to transpose the following array in NumPy?
# importing python module named numpy
import numpy as np
 
# making a 3x3 array
gfg = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
 
# before transpose
print(gfg, end ='\n\n')
 
# after transpose
print(gfg.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [13]:
#11.Perform the following operation using Python 


import numpy as np

B1= [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

B2=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

gfg1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

gfg2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])


#(a) Index wiLe multiplication

print(np.multiply(gfg1,gfg2))

#(b)Matrix multiplication

print(np.dot(gfg1, gfg2.T))

#(c)Add both the matricx

print(np.add(gfg1, gfg2))


#(d)Subtract matrix B from A

print(np.subtract(gfg1, gfg2))


#(e)Divide Matrix B by A

print(np.divide(gfg1, gfg2))


[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#12.Which function in Numpy can be used to swap the byte order of an array
The numpy.ndarray.byteswap() function toggles between the two representations: bigendian and little-endian.

Live Demo
import numpy as np 
a = np.array([1, 256, 8755], dtype = np.int16) 

print 'Our array is:' 
print a  

print 'Representation of data in memory in hexadecimal form:'  
print map(hex,a)  
# byteswap() function swaps in place by passing True parameter 

print 'Applying byteswap() function:' 
print a.byteswap(True) 

print 'In hexadecimal form:' 
print map(hex,a) 
# We can see the bytes being swapped
It will produce the following output −

Our array is:
[1 256 8755]

Representation of data in memory in hexadecimal form:
['0x1', '0x100', '0x2233']

Applying byteswap() function:
[256 1 13090]

In hexadecimal form:
['0x100', '0x1', '0x3322']

In [4]:
#13.What is the significance of the np.linalg.inv function?

Inverse Matrix using NumPy
Python provides a very easy method to calculate the inverse of a matrix. The function numpy.linalg.inv() is available in the NumPy module and is used to compute the inverse matrix in Python.

Syntax: numpy.linalg.inv(a)

Parameters:

a: Matrix to be inverted
Returns:  Inverse of the matrix a.

Example 1: In this example, we will create a 3 by 3 NumPy array matrix and then convert it into an inverse matrix using the np.linalg.inv() function.

# Import required package
import numpy as np
 
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Calculating the inverse of the matrix
print(np.linalg.inv(A))
Output:

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Example 2: In this example, we will create a 4 by 4 NumPy array matrix and then convert it using np.linalg.inv() function into an inverse Matrix in Python.

# Import required package
import numpy as np
 
# Taking a 4 * 4 matrix
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])
 
# Calculating the inverse of the matrix
print(np.linalg.inv(A))
Output:

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]

In [5]:
#14What does the np.reshape function do, and how is it used?

The numpy.reshape() function allows us to reshape an array in Python. Reshaping basically means, changing the shape of an array. And the shape of an array is determined by the number of elements in each dimension.

Reshaping allows us to add or remove dimensions in an array. We can also change the number of elements in each dimension.

Syntax and parameters
Here is the syntax of the function:

numpy.reshape(array, shape, order = 'C')
array: Input array.
shape: Integers or tuples of integers.
order: C-contiguous, F-contiguous, A-contiguous; this is an optional parameter.‘C’ order means that operating row-rise on the array will be slightly quicker. ‘F’ order means that column-wise operations will be faster. ‘A’ means to read / write the elements in Fortran-like index order.
Return value: An array which is reshaped without any change to its data.

How to use the numpy.reshape() method in Python?
Let’s take the following one-dimensional NumPy array as an example.

Input:
import numpy as np

x = np.arange(20)
        
#prints out the array with its elements
print(x)
print()
        
#prints out the shape of the array 
print(x.shape)
print()
        
#prints out the dimension value of the array
print(x.ndim)
Output:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

(20,)
            
1

In [6]:
#15.What is broadcasting in Numpy?
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b
array([2.,  4.,  6.])
NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b
array([2.,  4.,  6.])
The result is equivalent to the previous example where b was an array. We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as a.
